# Fichier de départ pour le 'build' de l'application wordpress
FROM wordpress
WORKDIR /var/www/html/
COPY simple-style/ ./wp-content/themes/simple-style/
COPY code-prettify/ ./wp-content/plugins/code-prettify/
